<!-- PCC Message box popup html companion for msgbox javascript -->
<div id="pcc-message-box" class="modal fade" tabindex="-1" aria-labelledby="pccPopupLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title fs-5"></h2>
        <button type="button" class="btn-close close" title="Close" data-bs-dismiss="modal" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <!-- Insert extra buttons/commands here -->
        <button type="button" class="btn btn-secondary modal-close" title="Close" data-bs-dismiss="modal" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- END PCC Message box popup html companion for msgbox javascript -->
